name: makanan_info
description: "Aplikasi Direktori Restoran & Menu"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- BACKEND ---
  supabase_flutter: ^2.8.3

  # --- STATE MANAGEMENT ---
  provider: ^6.1.2

  # --- UTILITIES ---
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  uuid: ^4.5.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/